os: Visual Studio 2015

platform: x64

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - choco install strawberryperl
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - git clone https://github.com/rakudo/rakudo.git %APPVEYOR_BUILD_FOLDER%\..\rakudo
  - cd %APPVEYOR_BUILD_FOLDER%\..\rakudo
  - perl Configure.pl --gen-moar --gen-nqp
  - nmake install
  - SET PATH=%APPVEYOR_BUILD_FOLDER%\..\rakudo\install\bin;%PATH%
  - SET ZEF_PLUGIN_DEBUG=1
  - SET ZEF_BUILDPM_DEBUG=1
  - cd %APPVEYOR_BUILD_FOLDER%

build: off

test_script:
    # test local path install
    - perl6 -Ilib bin/zef --verbose install .

    # Setup PATH to give access to the `zef` command (shown in stdout of prev command)
    - SET PATH=%APPVEYOR_BUILD_FOLDER%\..\rakudo\install\share\perl6\site\bin;%PATH%

    # change path to make sure next `zef` commands aren't using any files in cwd or lib/
    - cd %APPVEYOR_BUILD_FOLDER%\..

    # test identity install
    - zef -v install Base64

    # test bells and whistles
    - zef -v list
    - zef -v --installed list
    - zef -v search Base64
    - zef -v info Base64

on_success:
    # test uri install; may fail due to server issues
    #- zef -v install http://hack.p6c.org:5001/authors/id/P/PS/PSIXDISTS/Perl6/CSV-Parser-0.000.002_1601022004.tar.gz && exit 0
    # don't know how to make app veyor force this command as not required for pass

shallow_clone: true
