language: perl
perl:
    - '5.20'
env:
    - BACKEND=moar
    - BACKEND=jvm
    - BACKEND=parrot
matrix:
    allow_failures:
        - env: BACKEND=jvm
        - env: BACKEND=parrot
    fast_finish: true
before_install:
    - 'if [ "$BACKEND" == "parrot" ]; then sudo apt-get update -qq; fi;'
    - 'if [ "$BACKEND" == "parrot" ]; then sudo apt-get install -qq libicu48 libicu-dev; fi;'
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init # helpers for parallel testing/testing dirs
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:$PATH
    - rakudobrew build $BACKEND
    - perl6 -v
    - rakudobrew build-panda
install:
    # bootstrapping our test process with panda for now :)
    - panda install HTTP::UserAgent IO::Socket::SSL --notests
script:
    - prove -v -s -j$(test-jobs) -e "perl6 --ll-exception -Ilib" $(test-files)
after_success:
    - perl6 -Ilib bin/zef test t/ # check things run without prove