language: perl
perl:
    - '5.20'
env:
    - BACKEND=moar
    - BACKEND=jvm
matrix:
    allow_failures:
        - env: BACKEND=jvm
    fast_finish: true
sudo: false
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:$PATH
    - rakudobrew build $BACKEND
install:
    # need at least 1 statement in 'install'
    - perl6 -v
script:
    - perl6 -Ilib bin/zef -v --boring test
after_success:
    # We don't have time to do all of these on jvm, but they are mostly redundant anyway
    # (tests use the default blib so would otherwise break the test itself)
    - perl6 -Ilib bin/zef --save-to=precomp/ build ./
    - 'if [[ $BACKEND == "moar" ]]; then prove -j4 -v -e "perl6 -Iprecomp/lib" t/; fi'
    - perl6 -Iprecomp/lib bin/zef -v --report --boring install P6TCI
    - perl6 -e 'use P6TCI;'
    - 'if [[ $BACKEND == "moar" ]]; then perl6 -Iprecomp/lib bin/zef -v --report --boring --async install Zef; fi'
