language: perl
perl:
    - '5.20'
env:
    - BACKEND=moar ASYNC=True  REPORT=False
    - BACKEND=moar ASYNC=False REPORT=True
    - BACKEND=jvm  ASYNC=False REPORT=True
matrix:
    allow_failures:
        - env: BACKEND=jvm
    fast_finish: true
sudo: false
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:$PATH
    - rakudobrew build $BACKEND
install:
    # need at least 1 statement in 'install'
    - perl6 -v
script:
    - prove -j4 -v -e "perl6 -Ilib" t/
after_success:
    - perl6 -Ilib bin/zef --save-to=precomp/ build ./
    - perl6 -Iprecomp/lib bin/zef -v --boring test
    - perl6 -Iprecomp/lib bin/zef -v --boring --report=$REPORT --async=$ASYNC install Zef
