language: perl
perl:
    - '5.20'
env:
    - BACKEND=moar
    - BACKEND=jvm
matrix:
    allow_failures:
        - env: BACKEND=jvm
    fast_finish: true
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:$PATH
    - rakudobrew build $BACKEND
    - perl6 -v
    - rakudobrew build-panda
install:
    # bootstrapping our test process with panda for now :)
    - panda --notests installdeps .
script:
    - prove -v -e "perl6 -Ilib" t/
    - rm -rf blib/
    - perl6 -Ilib bin/zef build
    - mv blib/ blib-testing/
    - prove -v -e "perl6 -Iblib-testing/lib" t/
