language: perl
perl:
    - '5.20'
env:
    - BACKEND=moar JOBS=""
    - BACKEND=moar JOBS="--jobs=4"
    - BACKEND=jvm  JOBS=""
matrix:
    allow_failures:
        - env: BACKEND=jvm  JOBS=""
    fast_finish: true
sudo: false
before_install:
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:$PATH
    - rakudobrew build $BACKEND
install:
    # need at least 1 statement in 'install'
    - perl6 -v
script:
    - prove -j4 -v -e "perl6 -Ilib" t/ xt/
after_success:
    - 'if [[ $BACKEND == "moar" ]]; then perl6 -Ilib bin/zef -v --boring $JOBS --save-to=precomp/ build; fi'
    - 'if [[ $BACKEND == "moar" ]]; then perl6 -Iprecomp bin/zef -v --boring --lib=precomp $JOBS install Zef; fi'
